### ISSUE TITLE
Publish `@local` supporting version on npm

### ISSUE THREAD

**Issue by dralletje** [lezer-parser/lezer-grammar#1]
Not the most fun issue, but would help me out a lot :D

**Comment by marijnh** [comment]
What makes you think the current versions on npm don't support this?

**Comment by dralletje** [comment]
When I update with npm or yarn, `@local tokens` blocks don't get parsed correctly.
Also the commit for `@local tokens` is a month old and the last version published on npm is 8 months old.

**Comment by marijnh** [comment]
Which npm package are you looking at?

**Comment by dralletje** [comment]
https://www.npmjs.com/package/@lezer/lezer

**Comment by marijnh** [comment]
That's the Lezer grammar file parser (and definitely doesn't come with a lezer-generator command). Try @lezer/generator.

**Comment by dralletje** [comment]
This repo is also the Lezer grammar file parser, right?
I want the Lezer grammar that supports `@local` so I can highlight them in my lezer editor 😁

**Comment by marijnh** [comment]
Oh, *now* I get what you mean. Tagged 1.1.1

**Comment by dralletje** [comment]
Thanks!
